<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.
// Project implemented by the \"Recovery, Transformation and Resilience Plan.
// Funded by the European Union - Next GenerationEU\".
//
// Produced by the UNIMOODLE University Group: Universities of
// Valladolid, Complutense de Madrid, UPV/EHU, León, Salamanca,
// Illes Balears, Valencia, Rey Juan Carlos, La Laguna, Zaragoza, Málaga,
// Córdoba, Extremadura, Vigo, Las Palmas de Gran Canaria y Burgos.

/**
 * Version details
 *
 * @package    quizaccess_sebprogram
 * @copyright  2023 Proyecto UNIMOODLE
 * @author     UNIMOODLE Group (Coordinator) <direccion.area.estrategia.digital@uva.es>
 * @author     ISYC <soporte@isyc.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
namespace quizaccess_sebprogram\local\table;

use quizaccess_sebprogram\helper;
use quizaccess_sebprogram\program;
use quizaccess_sebprogram\program_controller;

defined('MOODLE_INTERNAL') || die();

require_once($CFG->libdir.'/tablelib.php');

/**
 * Templates table.
 *
 * @copyright  2020 Catalyst IT
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class program_dependency_list extends \flexible_table {

    /**
     * @var int Autogenerated id.
     */
    private static $autoid = 0;

    /**
     * Constructor
     *
     * @param string|null $id to be used by the table, autogenerated if null.
     */
    public function __construct($id = null) {
        global $PAGE;

        $id = (is_null($id) ? self::$autoid++ : $id);
        parent::__construct('quizaccess_sebprogram' . $id);

        $this->define_baseurl($PAGE->url);
        $this->set_attribute('class', 'generaltable admintable');

        // Column definition.
        $this->define_columns([
            'title',
            'executable',
            'originalname',
            'actions',
        ]);

        $this->define_headers([
            get_string('title', 'quizaccess_sebprogram'),
            get_string('executable', 'quizaccess_sebprogram'),
            get_string('originalname', 'quizaccess_sebprogram'),
            get_string('actions'),
        ]);

        $this->setup();
    }

    /**
     * Display name column.
     *
     * @param \quizaccess_sebprogram\program $data Template for this row.
     * @return string
     */
    protected function col_title(program $data) : string {
        return \html_writer::link(
            new \moodle_url(program_controller::get_base_url(), [
                'id' => $data->get('id'),
                'action' => program_controller::ACTION_EDIT,
            ]),
            $data->get('title')
        );
    }

    /**
     * Display exacutable.
     *
     * @param program $data description
     * @return string
     */
    protected function col_executable(program $data) : string {
        return $data->get('executable');
    }

    /**
     * Display originalname column.
     *
     * @param program $data description
     * @return string
     */
    protected function col_originalname(program $data): string {
        return $data->get('originalname');
    }


    /**
     * Display action column.
     *
     * @param program $data description
     * @return string
     */
    protected function col_actions(program $data) : string {
        $actions = [];

        $actions[] = helper::format_icon_link(
            new \moodle_url(program_controller::get_base_url(), [
                'id'        => $data->get('id'),
                'action'    => program_controller::ACTION_EDIT,
            ]),
            't/edit',
            get_string('edit')
        );

        $actions[] = helper::format_icon_link(
            new \moodle_url(program_controller::get_base_url(), [
                'id'        => $data->get('id'),
                'action'    => program_controller::ACTION_DELETE,
                'sesskey'   => sesskey(),
            ]),
            't/delete',
            get_string('delete'),
            null,
            [
            'data-action' => 'delete',
            'data-id' => $data->get('id'),
            ]
        );

        return implode('&nbsp;', $actions);
    }

    /**
     * Sets the data of the table.
     *
     * @param \quizaccess_sebprogram\program[] $records An array with records.
     */
    public function display(array $records) {
        foreach ($records as $record) {
            $this->add_data_keyed($this->format_row($record));
        }

        $this->finish_output();
    }

}
