Search.appendIndex(
    [
                {
            "fqsen": "\\backup_quizaccess_sebprogram_subplugin",
            "name": "backup_quizaccess_sebprogram_subplugin",
            "summary": "Provides\u0020the\u0020information\u0020to\u0020backup\u0020the\u0020honestycheck\u0020quiz\u0020access\u0020plugin.",
            "url": "classes/backup-quizaccess-sebprogram-subplugin.html"
        },                {
            "fqsen": "\\backup_quizaccess_sebprogram_subplugin\u003A\u003Adefine_quiz_subplugin_structure\u0028\u0029",
            "name": "define_quiz_subplugin_structure",
            "summary": "Defines\u0020the\u0020quiz\u0020subplugin\u0020structure.",
            "url": "classes/backup-quizaccess-sebprogram-subplugin.html#method_define_quiz_subplugin_structure"
        },                {
            "fqsen": "\\restore_quizaccess_sebprogram_subplugin",
            "name": "restore_quizaccess_sebprogram_subplugin",
            "summary": "Provides\u0020the\u0020information\u0020to\u0020restore\u0020the\u0020honestycheck\u0020quiz\u0020access\u0020plugin.",
            "url": "classes/restore-quizaccess-sebprogram-subplugin.html"
        },                {
            "fqsen": "\\restore_quizaccess_sebprogram_subplugin\u003A\u003Adefine_quiz_subplugin_structure\u0028\u0029",
            "name": "define_quiz_subplugin_structure",
            "summary": "A\u0020method\u0020to\u0020define\u0020the\u0020structure\u0020of\u0020the\u0020quiz\u0020subplugin.",
            "url": "classes/restore-quizaccess-sebprogram-subplugin.html#method_define_quiz_subplugin_structure"
        },                {
            "fqsen": "\\restore_quizaccess_sebprogram_subplugin\u003A\u003Aprocess_quizaccess_sebprogram\u0028\u0029",
            "name": "process_quizaccess_sebprogram",
            "summary": "Processes\u0020the\u0020quizaccess_sebprogram\u0020element,\u0020if\u0020it\u0020is\u0020in\u0020the\u0020file.",
            "url": "classes/restore-quizaccess-sebprogram-subplugin.html#method_process_quizaccess_sebprogram"
        },                {
            "fqsen": "\\restore_quizaccess_sebprogram_subplugin\u003A\u003Aprocess_quizaccess_program_quiz\u0028\u0029",
            "name": "process_quizaccess_program_quiz",
            "summary": "",
            "url": "classes/restore-quizaccess-sebprogram-subplugin.html#method_process_quizaccess_program_quiz"
        },                {
            "fqsen": "\\restore_quizaccess_sebprogram_subplugin\u003A\u003A\u0024last_inserted_id",
            "name": "last_inserted_id",
            "summary": "",
            "url": "classes/restore-quizaccess-sebprogram-subplugin.html#property_last_inserted_id"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager",
            "name": "access_manager",
            "summary": "Manage\u0020the\u0020access\u0020to\u0020the\u0020quiz.",
            "url": "classes/quizaccess-sebprogram-access-manager.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "The\u0020access_manager\u0020constructor.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method___construct"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Avalidate_browser_exam_key\u0028\u0029",
            "name": "validate_browser_exam_key",
            "summary": "Validate\u0020browser\u0020exam\u0020key.\u0020It\u0020will\u0020validate\u0020a\u0020provided\u0020browser\u0020exam\u0020key\u0020if\u0020provided,\u0020then\u0020will\u0020fall\u0020back\u0020to\u0020checking\nthe\u0020header.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_validate_browser_exam_key"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Avalidate_config_key\u0028\u0029",
            "name": "validate_config_key",
            "summary": "Validate\u0020a\u0020config\u0020key.\u0020It\u0020will\u0020check\u0020a\u0020provided\u0020config\u0020key\u0020if\u0020provided\u0020then\u0020will\u0020fall\u0020back\u0020to\u0020checking\u0020config\nkey\u0020in\u0020header.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_validate_config_key"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Aseb_required\u0028\u0029",
            "name": "seb_required",
            "summary": "Check\u0020if\u0020Safe\u0020Exam\u0020Browser\u0020is\u0020required\u0020to\u0020access\u0020quiz.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_seb_required"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Avalidate_basic_header\u0028\u0029",
            "name": "validate_basic_header",
            "summary": "This\u0020is\u0020the\u0020basic\u0020check\u0020for\u0020the\u0020Safe\u0020Exam\u0020Browser\u0020previously\u0020used\u0020in\u0020the\u0020quizaccess_safebrowser\u0020plugin\u0020that\nmanaged\u0020basic\u0020Moodle\u0020interactions\u0020with\u0020SEB.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_validate_basic_header"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Ais_using_seb\u0028\u0029",
            "name": "is_using_seb",
            "summary": "Check\u0020if\u0020using\u0020Safe\u0020Exam\u0020Browser.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_is_using_seb"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Acan_bypass_seb\u0028\u0029",
            "name": "can_bypass_seb",
            "summary": "Check\u0020if\u0020user\u0020has\u0020any\u0020capability\u0020to\u0020bypass\u0020the\u0020Safe\u0020Exam\u0020Browser\u0020requirement.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_can_bypass_seb"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Aget_this_page_url\u0028\u0029",
            "name": "get_this_page_url",
            "summary": "Return\u0020the\u0020full\u0020URL\u0020that\u0020was\u0020used\u0020to\u0020request\u0020the\u0020current\u0020page,\u0020which\u0020is\nwhat\u0020we\u0020need\u0020for\u0020verifying\u0020the\u0020X\u002DSafeExamBrowser\u002DRequestHash\u0020header.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_get_this_page_url"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Aget_valid_config_key\u0028\u0029",
            "name": "get_valid_config_key",
            "summary": "Return\u0020expected\u0020SEB\u0020config\u0020key.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_get_valid_config_key"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Aget_quiz\u0028\u0029",
            "name": "get_quiz",
            "summary": "Getter\u0020for\u0020the\u0020quiz\u0020object.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_get_quiz"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Ais_allowed_browser_examkeys_configured\u0028\u0029",
            "name": "is_allowed_browser_examkeys_configured",
            "summary": "Check\u0020that\u0020at\u0020least\u0020one\u0020browser\u0020exam\u0020key\u0020exists\u0020in\u0020the\u0020quiz\u0020settings.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_is_allowed_browser_examkeys_configured"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Acheck_browser_exam_keys\u0028\u0029",
            "name": "check_browser_exam_keys",
            "summary": "Check\u0020the\u0020hash\u0020from\u0020the\u0020request\u0020header\u0020against\u0020the\u0020permitted\u0020browser\u0020exam\u0020keys.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_check_browser_exam_keys"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Acheck_key\u0028\u0029",
            "name": "check_key",
            "summary": "Check\u0020the\u0020hash\u0020from\u0020the\u0020request\u0020header\u0020against\u0020a\u0020single\u0020permitted\u0020key.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_check_key"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Aget_received_config_key\u0028\u0029",
            "name": "get_received_config_key",
            "summary": "Returns\u0020Safe\u0020Exam\u0020Browser\u0020Config\u0020Key\u0020hash.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_get_received_config_key"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Aget_received_browser_exam_key\u0028\u0029",
            "name": "get_received_browser_exam_key",
            "summary": "Returns\u0020the\u0020Browser\u0020Exam\u0020Key\u0020hash.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_get_received_browser_exam_key"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Aget_seb_use_type\u0028\u0029",
            "name": "get_seb_use_type",
            "summary": "Get\u0020type\u0020of\u0020SEB\u0020usage\u0020for\u0020the\u0020quiz.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_get_seb_use_type"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Ashould_validate_basic_header\u0028\u0029",
            "name": "should_validate_basic_header",
            "summary": "Should\u0020validate\u0020basic\u0020header\u003F",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_should_validate_basic_header"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Ashould_validate_config_key\u0028\u0029",
            "name": "should_validate_config_key",
            "summary": "Should\u0020validate\u0020SEB\u0020config\u0020key\u003F",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_should_validate_config_key"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Ashould_validate_browser_exam_key\u0028\u0029",
            "name": "should_validate_browser_exam_key",
            "summary": "Should\u0020validate\u0020browser\u0020exam\u0020key\u003F",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_should_validate_browser_exam_key"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Aset_session_access\u0028\u0029",
            "name": "set_session_access",
            "summary": "Set\u0020session\u0020access\u0020for\u0020quiz.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_set_session_access"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Avalidate_session_access\u0028\u0029",
            "name": "validate_session_access",
            "summary": "Check\u0020session\u0020access\u0020for\u0020quiz\u0020if\u0020already\u0020set.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_validate_session_access"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Aclear_session_access\u0028\u0029",
            "name": "clear_session_access",
            "summary": "Unset\u0020the\u0020global\u0020session\u0020access\u0020variable\u0020for\u0020this\u0020quiz.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_clear_session_access"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Aredirect_to_seb_config_link\u0028\u0029",
            "name": "redirect_to_seb_config_link",
            "summary": "Redirect\u0020to\u0020SEB\u0020config\u0020link.\u0020This\u0020will\u0020force\u0020Safe\u0020Exam\u0020Browser\u0020to\u0020be\u0020reconfigured.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_redirect_to_seb_config_link"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003Ashould_redirect_to_seb_config_link\u0028\u0029",
            "name": "should_redirect_to_seb_config_link",
            "summary": "Check\u0020if\u0020we\u0020need\u0020to\u0020redirect\u0020to\u0020SEB\u0020config\u0020link.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#method_should_redirect_to_seb_config_link"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003ACONFIG_KEY_HEADER",
            "name": "CONFIG_KEY_HEADER",
            "summary": "Header\u0020sent\u0020by\u0020Safe\u0020Exam\u0020Browser\u0020containing\u0020the\u0020Config\u0020Key\u0020hash.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#constant_CONFIG_KEY_HEADER"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003ABROWSER_EXAM_KEY_HEADER",
            "name": "BROWSER_EXAM_KEY_HEADER",
            "summary": "Header\u0020sent\u0020by\u0020Safe\u0020Exam\u0020Browser\u0020containing\u0020the\u0020Browser\u0020Exam\u0020Key\u0020hash.",
            "url": "classes/quizaccess-sebprogram-access-manager.html#constant_BROWSER_EXAM_KEY_HEADER"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003A\u0024quiz",
            "name": "quiz",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-access-manager.html#property_quiz"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003A\u0024quizsettings",
            "name": "quizsettings",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-access-manager.html#property_quizsettings"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003A\u0024context",
            "name": "context",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-access-manager.html#property_context"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\access_manager\u003A\u003A\u0024validconfigkey",
            "name": "validconfigkey",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-access-manager.html#property_validconfigkey"
        },                {
            "fqsen": "\\quizaccess_sebprogram_admin_setting_display_programs",
            "name": "quizaccess_sebprogram_admin_setting_display_programs",
            "summary": "Class\u0020for\u0020glossary\u0020display\u0020formats\u0020management.",
            "url": "classes/quizaccess-sebprogram-admin-setting-display-programs.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram_admin_setting_display_programs\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Calls\u0020parent\u003A\u003A__construct\u0020with\u0020specific\u0020arguments",
            "url": "classes/quizaccess-sebprogram-admin-setting-display-programs.html#method___construct"
        },                {
            "fqsen": "\\quizaccess_sebprogram_admin_setting_display_programs\u003A\u003Aget_setting\u0028\u0029",
            "name": "get_setting",
            "summary": "Always\u0020returns\u0020true,\u0020does\u0020nothing",
            "url": "classes/quizaccess-sebprogram-admin-setting-display-programs.html#method_get_setting"
        },                {
            "fqsen": "\\quizaccess_sebprogram_admin_setting_display_programs\u003A\u003Aget_defaultsetting\u0028\u0029",
            "name": "get_defaultsetting",
            "summary": "Always\u0020returns\u0020true,\u0020does\u0020nothing",
            "url": "classes/quizaccess-sebprogram-admin-setting-display-programs.html#method_get_defaultsetting"
        },                {
            "fqsen": "\\quizaccess_sebprogram_admin_setting_display_programs\u003A\u003Awrite_setting\u0028\u0029",
            "name": "write_setting",
            "summary": "Always\u0020returns\u0020\u0027\u0027,\u0020does\u0020not\u0020write\u0020anything",
            "url": "classes/quizaccess-sebprogram-admin-setting-display-programs.html#method_write_setting"
        },                {
            "fqsen": "\\quizaccess_sebprogram_admin_setting_display_programs\u003A\u003Aoutput_html\u0028\u0029",
            "name": "output_html",
            "summary": "Builds\u0020the\u0020XHTML\u0020to\u0020display\u0020the\u0020control",
            "url": "classes/quizaccess-sebprogram-admin-setting-display-programs.html#method_output_html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\event\\access_prevented",
            "name": "access_prevented",
            "summary": "Event\u0020for\u0020when\u0020access\u0020to\u0020a\u0020quiz\u0020is\u0020prevented\u0020by\u0020this\u0020subplugin.",
            "url": "classes/quizaccess-sebprogram-event-access-prevented.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\event\\access_prevented\u003A\u003Acreate_strict\u0028\u0029",
            "name": "create_strict",
            "summary": "Create\u0020event\u0020with\u0020strict\u0020parameters.",
            "url": "classes/quizaccess-sebprogram-event-access-prevented.html#method_create_strict"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\event\\access_prevented\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "Initialize\u0020the\u0020event\u0020data.",
            "url": "classes/quizaccess-sebprogram-event-access-prevented.html#method_init"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\event\\access_prevented\u003A\u003Aget_name\u0028\u0029",
            "name": "get_name",
            "summary": "Get\u0020the\u0020name\u0020of\u0020the\u0020event.",
            "url": "classes/quizaccess-sebprogram-event-access-prevented.html#method_get_name"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\event\\access_prevented\u003A\u003Aget_description\u0028\u0029",
            "name": "get_description",
            "summary": "Returns\u0020non\u002Dlocalised\u0020event\u0020description\u0020with\u0020id\u0027s\u0020for\u0020admin\u0020use\u0020only.",
            "url": "classes/quizaccess-sebprogram-event-access-prevented.html#method_get_description"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\event\\access_prevented\u003A\u003Aget_objectid_mapping\u0028\u0029",
            "name": "get_objectid_mapping",
            "summary": "This\u0020is\u0020used\u0020when\u0020restoring\u0020course\u0020logs\u0020where\u0020it\u0020is\u0020required\u0020that\u0020we\nmap\u0020the\u0020objectid\u0020to\u0020it\u0027s\u0020new\u0020value\u0020in\u0020the\u0020new\u0020course.",
            "url": "classes/quizaccess-sebprogram-event-access-prevented.html#method_get_objectid_mapping"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\event\\access_prevented\u003A\u003Aget_other_mapping\u0028\u0029",
            "name": "get_other_mapping",
            "summary": "This\u0020is\u0020used\u0020when\u0020restoring\u0020course\u0020logs\u0020where\u0020it\u0020is\u0020required\u0020that\u0020we\nmap\u0020the\u0020information\u0020in\u0020\u0027other\u0027\u0020to\u0020it\u0027s\u0020new\u0020value\u0020in\u0020the\u0020new\u0020course.",
            "url": "classes/quizaccess-sebprogram-event-access-prevented.html#method_get_other_mapping"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\helper",
            "name": "helper",
            "summary": "Helper\u0020class.",
            "url": "classes/quizaccess-sebprogram-helper.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\helper\u003A\u003Aformat_icon_link\u0028\u0029",
            "name": "format_icon_link",
            "summary": "Get\u0020a\u0020filler\u0020icon\u0020for\u0020display\u0020in\u0020the\u0020actions\u0020column\u0020of\u0020a\u0020table.",
            "url": "classes/quizaccess-sebprogram-helper.html#method_format_icon_link"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\helper\u003A\u003Ais_valid_seb_config\u0028\u0029",
            "name": "is_valid_seb_config",
            "summary": "Validate\u0020seb\u0020config\u0020string.",
            "url": "classes/quizaccess-sebprogram-helper.html#method_is_valid_seb_config"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\helper\u003A\u003Aget_seb_config_content\u0028\u0029",
            "name": "get_seb_config_content",
            "summary": "Get\u0020seb\u0020config\u0020content\u0020for\u0020a\u0020particular\u0020quiz.\u0020This\u0020method\u0020checks\u0020caps.",
            "url": "classes/quizaccess-sebprogram-helper.html#method_get_seb_config_content"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\helper\u003A\u003Aattach_extra_config_content\u0028\u0029",
            "name": "attach_extra_config_content",
            "summary": "Attach\u0020extra\u0020config\u0020content\u0020to\u0020the\u0020given\u0020config\u0020based\u0020on\u0020the\u0020quiz\u0020ID.",
            "url": "classes/quizaccess-sebprogram-helper.html#method_attach_extra_config_content"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\helper\u003A\u003Aget_seb_file_headers\u0028\u0029",
            "name": "get_seb_file_headers",
            "summary": "A\u0020helper\u0020function\u0020to\u0020get\u0020a\u0020list\u0020of\u0020seb\u0020config\u0020file\u0020headers.",
            "url": "classes/quizaccess-sebprogram-helper.html#method_get_seb_file_headers"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\helper\u003A\u003Asend_seb_config_file\u0028\u0029",
            "name": "send_seb_config_file",
            "summary": "Serve\u0020a\u0020file\u0020to\u0020browser\u0020for\u0020download.",
            "url": "classes/quizaccess-sebprogram-helper.html#method_send_seb_config_file"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template",
            "name": "template",
            "summary": "Form\u0020for\u0020manipulating\u0020with\u0020the\u0020template\u0020records.",
            "url": "classes/quizaccess-sebprogram-local-form-template.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Form\u0020definition.",
            "url": "classes/quizaccess-sebprogram-local-form-template.html#method_definition"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template\u003A\u003Aextra_validation\u0028\u0029",
            "name": "extra_validation",
            "summary": "Extra\u0020validation.",
            "url": "classes/quizaccess-sebprogram-local-form-template.html#method_extra_validation"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template\u003A\u003Aget_program_select_list\u0028\u0029",
            "name": "get_program_select_list",
            "summary": "Get\u0020the\u0020program\u0020select\u0020list.",
            "url": "classes/quizaccess-sebprogram-local-form-template.html#method_get_program_select_list"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template\u003A\u003Aget_records_program_select\u0028\u0029",
            "name": "get_records_program_select",
            "summary": "Get\u0020the\u0020records\u0020from\u0020the\u0020program\u0020select.",
            "url": "classes/quizaccess-sebprogram-local-form-template.html#method_get_records_program_select"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template\u003A\u003Aset_all_program_list\u0028\u0029",
            "name": "set_all_program_list",
            "summary": "Set\u0020all\u0020program\u0020list.",
            "url": "classes/quizaccess-sebprogram-local-form-template.html#method_set_all_program_list"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template\u003A\u003A\u0024persistentclass",
            "name": "persistentclass",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-local-form-template.html#property_persistentclass"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template\u003A\u003A\u0024programlist",
            "name": "programlist",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-local-form-template.html#property_programlist"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template\u003A\u003A\u0024recordsprogramselect",
            "name": "recordsprogramselect",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-local-form-template.html#property_recordsprogramselect"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template\u003A\u003A\u0024programselectlist",
            "name": "programselectlist",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-local-form-template.html#property_programselectlist"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template_course",
            "name": "template_course",
            "summary": "Form\u0020for\u0020manipulating\u0020with\u0020the\u0020template\u0020records.",
            "url": "classes/quizaccess-sebprogram-local-form-template-course.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template_course\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Form\u0020definition.",
            "url": "classes/quizaccess-sebprogram-local-form-template-course.html#method_definition"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template_course\u003A\u003Aextra_validation\u0028\u0029",
            "name": "extra_validation",
            "summary": "Extra\u0020validation.",
            "url": "classes/quizaccess-sebprogram-local-form-template-course.html#method_extra_validation"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template_course\u003A\u003Aget_program_select_list\u0028\u0029",
            "name": "get_program_select_list",
            "summary": "Get\u0020the\u0020program\u0020select\u0020list.",
            "url": "classes/quizaccess-sebprogram-local-form-template-course.html#method_get_program_select_list"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template_course\u003A\u003Aget_records_program_select\u0028\u0029",
            "name": "get_records_program_select",
            "summary": "Get\u0020the\u0020records\u0020program\u0020select.",
            "url": "classes/quizaccess-sebprogram-local-form-template-course.html#method_get_records_program_select"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template_course\u003A\u003Aset_all_program_list\u0028\u0029",
            "name": "set_all_program_list",
            "summary": "Sets\u0020the\u0020all\u0020program\u0020list\u0020for\u0020a\u0020given\u0020program\u0020ID.",
            "url": "classes/quizaccess-sebprogram-local-form-template-course.html#method_set_all_program_list"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template_course\u003A\u003A\u0024persistentclass",
            "name": "persistentclass",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-local-form-template-course.html#property_persistentclass"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template_course\u003A\u003A\u0024programlist",
            "name": "programlist",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-local-form-template-course.html#property_programlist"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template_course\u003A\u003A\u0024recordsprogramselect",
            "name": "recordsprogramselect",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-local-form-template-course.html#property_recordsprogramselect"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form\\template_course\u003A\u003A\u0024programselectlist",
            "name": "programselectlist",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-local-form-template-course.html#property_programselectlist"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_dependency_list",
            "name": "program_dependency_list",
            "summary": "Templates\u0020table.",
            "url": "classes/quizaccess-sebprogram-local-table-program-dependency-list.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_dependency_list\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/quizaccess-sebprogram-local-table-program-dependency-list.html#method___construct"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_dependency_list\u003A\u003Acol_title\u0028\u0029",
            "name": "col_title",
            "summary": "Display\u0020name\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-dependency-list.html#method_col_title"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_dependency_list\u003A\u003Acol_executable\u0028\u0029",
            "name": "col_executable",
            "summary": "Display\u0020exacutable.",
            "url": "classes/quizaccess-sebprogram-local-table-program-dependency-list.html#method_col_executable"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_dependency_list\u003A\u003Acol_originalname\u0028\u0029",
            "name": "col_originalname",
            "summary": "Display\u0020originalname\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-dependency-list.html#method_col_originalname"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_dependency_list\u003A\u003Acol_actions\u0028\u0029",
            "name": "col_actions",
            "summary": "Display\u0020action\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-dependency-list.html#method_col_actions"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_dependency_list\u003A\u003Adisplay\u0028\u0029",
            "name": "display",
            "summary": "Sets\u0020the\u0020data\u0020of\u0020the\u0020table.",
            "url": "classes/quizaccess-sebprogram-local-table-program-dependency-list.html#method_display"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_dependency_list\u003A\u003A\u0024autoid",
            "name": "autoid",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-local-table-program-dependency-list.html#property_autoid"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list",
            "name": "program_list",
            "summary": "Templates\u0020table.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/quizaccess-sebprogram-local-table-program-list.html#method___construct"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list\u003A\u003Acol_title\u0028\u0029",
            "name": "col_title",
            "summary": "Display\u0020name\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list.html#method_col_title"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list\u003A\u003Acol_executable\u0028\u0029",
            "name": "col_executable",
            "summary": "Display\u0020executable\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list.html#method_col_executable"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list\u003A\u003Acol_originalname\u0028\u0029",
            "name": "col_originalname",
            "summary": "Display\u0020originalname\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list.html#method_col_originalname"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list\u003A\u003Acol_dependency\u0028\u0029",
            "name": "col_dependency",
            "summary": "Display\u0020dependecy\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list.html#method_col_dependency"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list\u003A\u003Acol_actions\u0028\u0029",
            "name": "col_actions",
            "summary": "A\u0020description\u0020of\u0020the\u0020entire\u0020PHP\u0020function.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list.html#method_col_actions"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list\u003A\u003Adisplay\u0028\u0029",
            "name": "display",
            "summary": "Sets\u0020the\u0020data\u0020of\u0020the\u0020table.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list.html#method_display"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list\u003A\u003A\u0024autoid",
            "name": "autoid",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-local-table-program-list.html#property_autoid"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list_course",
            "name": "program_list_course",
            "summary": "Templates\u0020table.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list-course.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list_course\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/quizaccess-sebprogram-local-table-program-list-course.html#method___construct"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list_course\u003A\u003Acol_title\u0028\u0029",
            "name": "col_title",
            "summary": "Display\u0020name\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list-course.html#method_col_title"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list_course\u003A\u003Acol_executable\u0028\u0029",
            "name": "col_executable",
            "summary": "Display\u0020executable\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list-course.html#method_col_executable"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list_course\u003A\u003Acol_originalname\u0028\u0029",
            "name": "col_originalname",
            "summary": "Display\u0020originalname\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list-course.html#method_col_originalname"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list_course\u003A\u003Acol_dependency\u0028\u0029",
            "name": "col_dependency",
            "summary": "Display\u0020dependency\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list-course.html#method_col_dependency"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list_course\u003A\u003Acol_numberofuses\u0028\u0029",
            "name": "col_numberofuses",
            "summary": "Display\u0020numberofuses\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list-course.html#method_col_numberofuses"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list_course\u003A\u003Acol_actions\u0028\u0029",
            "name": "col_actions",
            "summary": "Display\u0020actions\u0020column.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list-course.html#method_col_actions"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list_course\u003A\u003Adisplay\u0028\u0029",
            "name": "display",
            "summary": "Sets\u0020the\u0020data\u0020of\u0020the\u0020table.",
            "url": "classes/quizaccess-sebprogram-local-table-program-list-course.html#method_display"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table\\program_list_course\u003A\u003A\u0024autoid",
            "name": "autoid",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-local-table-program-list-course.html#property_autoid"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\privacy\\provider",
            "name": "provider",
            "summary": "Privacy\u0020Subsystem\u0020for\u0020quizaccess_programs\u0020implementing\u0020null_provider.",
            "url": "classes/quizaccess-sebprogram-privacy-provider.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\privacy\\provider\u003A\u003Aget_reason\u0028\u0029",
            "name": "get_reason",
            "summary": "Get\u0020the\u0020language\u0020string\u0020identifier\u0020with\u0020the\u0020component\u0027s\u0020language\nfile\u0020to\u0020explain\u0020why\u0020this\u0020plugin\u0020stores\u0020no\u0020data.",
            "url": "classes/quizaccess-sebprogram-privacy-provider.html#method_get_reason"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program",
            "name": "program",
            "summary": "A\u0020persistent\u0020class\u0020to\u0020store\u0020the\u0020SEB\u0020program\u0020details.",
            "url": "classes/quizaccess-sebprogram-program.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program\u003A\u003Adefine_properties\u0028\u0029",
            "name": "define_properties",
            "summary": "Return\u0020the\u0020definition\u0020of\u0020the\u0020properties\u0020of\u0020this\u0020model.",
            "url": "classes/quizaccess-sebprogram-program.html#method_define_properties"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program\u003A\u003Avalidate_content\u0028\u0029",
            "name": "validate_content",
            "summary": "Validate\u0020programs\u0020content.",
            "url": "classes/quizaccess-sebprogram-program.html#method_validate_content"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program\u003A\u003Acan_delete\u0028\u0029",
            "name": "can_delete",
            "summary": "Check\u0020if\u0020we\u0020can\u0020delete\u0020the\u0020programs.",
            "url": "classes/quizaccess-sebprogram-program.html#method_can_delete"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program\u003A\u003Aget_records_course\u0028\u0029",
            "name": "get_records_course",
            "summary": "Get\u0020records\u0020for\u0020a\u0020specific\u0020course.",
            "url": "classes/quizaccess-sebprogram-program.html#method_get_records_course"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program\u003A\u003Aget_records_generic_dependency\u0028\u0029",
            "name": "get_records_generic_dependency",
            "summary": "Retrieve\u0020records\u0020based\u0020on\u0020a\u0020generic\u0020dependency\u0020for\u0020a\u0020given\u0020program\u0020ID.",
            "url": "classes/quizaccess-sebprogram-program.html#method_get_records_generic_dependency"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program\u003A\u003ATABLE",
            "name": "TABLE",
            "summary": "Table\u0020name\u0020for\u0020the\u0020persistent.",
            "url": "classes/quizaccess-sebprogram-program.html#constant_TABLE"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program\u003A\u003A\u0024plistprogram",
            "name": "plistprogram",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-program.html#property_plistprogram"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program\u003A\u003A\u0024idcourse",
            "name": "idcourse",
            "summary": "The\u0020id\u0020of\u0020the\u0020course\u0020this\u0020program\u0020belongs\u0020to.",
            "url": "classes/quizaccess-sebprogram-program.html#property_idcourse"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_dependency",
            "name": "program_dependency",
            "summary": "The\u0020persistent\u0020that\u0020represents\u0020the\u0020dependency\u0020between\u0020a\u0020quiz\u0020and\u0020a\u0020SEB\u0020program.",
            "url": "classes/quizaccess-sebprogram-program-dependency.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_dependency\u003A\u003Adefine_properties\u0028\u0029",
            "name": "define_properties",
            "summary": "Return\u0020the\u0020definition\u0020of\u0020the\u0020properties\u0020of\u0020this\u0020model.",
            "url": "classes/quizaccess-sebprogram-program-dependency.html#method_define_properties"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_dependency\u003A\u003ATABLE",
            "name": "TABLE",
            "summary": "Table\u0020name\u0020for\u0020the\u0020persistent.",
            "url": "classes/quizaccess-sebprogram-program-dependency.html#constant_TABLE"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_dependency\u003A\u003A\u0024plistprogram",
            "name": "plistprogram",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-program-dependency.html#property_plistprogram"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_quiz",
            "name": "program_quiz",
            "summary": "Represent\u0020a\u0020SEB\u0020program\u0020and\u0020the\u0020quiz\u0020associated\u0020with\u0020it.",
            "url": "classes/quizaccess-sebprogram-program-quiz.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_quiz\u003A\u003Adefine_properties\u0028\u0029",
            "name": "define_properties",
            "summary": "Return\u0020the\u0020definition\u0020of\u0020the\u0020properties\u0020of\u0020this\u0020model.",
            "url": "classes/quizaccess-sebprogram-program-quiz.html#method_define_properties"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_quiz\u003A\u003ATABLE",
            "name": "TABLE",
            "summary": "Table\u0020name\u0020for\u0020the\u0020persistent.",
            "url": "classes/quizaccess-sebprogram-program-quiz.html#constant_TABLE"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_quiz\u003A\u003A\u0024plistprogram",
            "name": "plistprogram",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-program-quiz.html#property_plistprogram"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings",
            "name": "quiz_settings",
            "summary": "Entity\u0020model\u0020representing\u0020quiz\u0020settings\u0020for\u0020the\u0020seb\u0020plugin.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Adefine_properties\u0028\u0029",
            "name": "define_properties",
            "summary": "Return\u0020the\u0020definition\u0020of\u0020the\u0020properties\u0020of\u0020this\u0020model.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_define_properties"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aget_by_quiz_id\u0028\u0029",
            "name": "get_by_quiz_id",
            "summary": "Return\u0020an\u0020instance\u0020by\u0020quiz\u0020id.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_get_by_quiz_id"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aget_config_by_quiz_id\u0028\u0029",
            "name": "get_config_by_quiz_id",
            "summary": "Return\u0020cached\u0020SEB\u0020config\u0020represented\u0020as\u0020a\u0020string\u0020by\u0020quiz\u0020ID.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_get_config_by_quiz_id"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aget_config_key_by_quiz_id\u0028\u0029",
            "name": "get_config_key_by_quiz_id",
            "summary": "Return\u0020cached\u0020SEB\u0020config\u0020key\u0020by\u0020quiz\u0020ID.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_get_config_key_by_quiz_id"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aget_config_key_cache\u0028\u0029",
            "name": "get_config_key_cache",
            "summary": "Return\u0020SEB\u0020config\u0020key\u0020cache\u0020instance.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_get_config_key_cache"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aget_config_cache\u0028\u0029",
            "name": "get_config_cache",
            "summary": "Return\u0020SEB\u0020config\u0020cache\u0020instance.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_get_config_cache"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aget_quiz_settings_cache\u0028\u0029",
            "name": "get_quiz_settings_cache",
            "summary": "Return\u0020quiz\u0020settings\u0020cache\u0020object,",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_get_quiz_settings_cache"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aafter_create\u0028\u0029",
            "name": "after_create",
            "summary": "Adds\u0020the\u0020new\u0020record\u0020to\u0020the\u0020cache.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_after_create"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aafter_update\u0028\u0029",
            "name": "after_update",
            "summary": "Updates\u0020the\u0020cache\u0020record.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_after_update"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aafter_save\u0028\u0029",
            "name": "after_save",
            "summary": "Helper\u0020method\u0020to\u0020execute\u0020common\u0020stuff\u0020after\u0020create\u0020and\u0020update.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_after_save"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Abefore_delete\u0028\u0029",
            "name": "before_delete",
            "summary": "Removes\u0020unnecessary\u0020stuff\u0020from\u0020db.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_before_delete"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Avalidate_allowedbrowserexamkeys\u0028\u0029",
            "name": "validate_allowedbrowserexamkeys",
            "summary": "Validate\u0020the\u0020browser\u0020exam\u0020keys\u0020string.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_validate_allowedbrowserexamkeys"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aget_allowedbrowserexamkeys\u0028\u0029",
            "name": "get_allowedbrowserexamkeys",
            "summary": "Get\u0020the\u0020browser\u0020exam\u0020keys\u0020as\u0020a\u0020pre\u002Dsplit\u0020array\u0020instead\u0020of\u0020just\u0020as\u0020a\u0020string.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_get_allowedbrowserexamkeys"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Abefore_update\u0028\u0029",
            "name": "before_update",
            "summary": "Hook\u0020to\u0020execute\u0020before\u0020an\u0020update.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_before_update"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Abefore_create\u0028\u0029",
            "name": "before_create",
            "summary": "Hook\u0020to\u0020execute\u0020before\u0020a\u0020create.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_before_create"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Abefore_save\u0028\u0029",
            "name": "before_save",
            "summary": "As\u0020there\u0020is\u0020no\u0020hook\u0020for\u0020before\u0020both\u0020create\u0020and\u0020update,\u0020this\u0020function\u0020is\u0020called\u0020by\u0020both\u0020hooks.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_before_save"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Abefore_validate\u0028\u0029",
            "name": "before_validate",
            "summary": "Before\u0020validate\u0020hook.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_before_validate"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aprocess_configs\u0028\u0029",
            "name": "process_configs",
            "summary": "Create\u0020or\u0020update\u0020the\u0020config\u0020string\u0020based\u0020on\u0020the\u0020current\u0020quiz\u0020settings.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_process_configs"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aget_config_key\u0028\u0029",
            "name": "get_config_key",
            "summary": "Return\u0020SEB\u0020config\u0020key.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_get_config_key"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aget_config\u0028\u0029",
            "name": "get_config",
            "summary": "Return\u0020string\u0020representation\u0020of\u0020the\u0020config.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_get_config"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aprocess_seb_config_no\u0028\u0029",
            "name": "process_seb_config_no",
            "summary": "Case\u0020for\u0020USE_SEB_NO.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_process_seb_config_no"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aprocess_seb_config_manually\u0028\u0029",
            "name": "process_seb_config_manually",
            "summary": "Case\u0020for\u0020USE_SEB_CONFIG_MANUALLY.\u0020This\u0020creates\u0020a\u0020plist\u0020and\u0020applies\u0020all\u0020settings\u0020from\u0020the\u0020posted\u0020form,\u0020along\u0020with\nsome\u0020defaults.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_process_seb_config_manually"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aprocess_seb_client_config\u0028\u0029",
            "name": "process_seb_client_config",
            "summary": "Case\u0020for\u0020USE_SEB_CLIENT_CONFIG.\u0020This\u0020creates\u0020an\u0020empty\u0020plist\u0020to\u0020remove\u0020the\u0020config\u0020stored.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_process_seb_client_config"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aprocess_required_enforced_settings\u0028\u0029",
            "name": "process_required_enforced_settings",
            "summary": "Sets\u0020or\u0020updates\u0020some\u0020sensible\u0020default\u0020settings,\u0020these\u0020are\u0020the\u0020items\u0020\u0027startURL\u0027\u0020and\u0020\u0027sendBrowserExamKey\u0027.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_process_required_enforced_settings"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aprocess_bool_settings\u0028\u0029",
            "name": "process_bool_settings",
            "summary": "Use\u0020the\u0020boolean\u0020map\u0020to\u0020add\u0020Moodle\u0020boolean\u0020setting\u0020to\u0020config\u0020PList.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_process_bool_settings"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aprocess_bool_setting\u0028\u0029",
            "name": "process_bool_setting",
            "summary": "Process\u0020provided\u0020single\u0020bool\u0020setting.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_process_bool_setting"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aprocess_quit_password_settings\u0028\u0029",
            "name": "process_quit_password_settings",
            "summary": "Turn\u0020hashed\u0020quit\u0020password\u0020and\u0020quit\u0020link\u0020into\u0020PList\u0020strings\u0020and\u0020add\u0020to\u0020config\u0020PList.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_process_quit_password_settings"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aprocess_quit_url_from_settings\u0028\u0029",
            "name": "process_quit_url_from_settings",
            "summary": "Sets\u0020the\u0020quitURL\u0020if\u0020found\u0020in\u0020the\u0020quiz_settings.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_process_quit_url_from_settings"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aprocess_url_filters\u0028\u0029",
            "name": "process_url_filters",
            "summary": "Turn\u0020return\u0020separated\u0020strings\u0020for\u0020URL\u0020filters\u0020into\u0020a\u0020PList\u0020array\u0020and\u0020add\u0020to\u0020config\u0020PList.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_process_url_filters"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Acreate_filter_rule\u0028\u0029",
            "name": "create_filter_rule",
            "summary": "Create\u0020a\u0020CFDictionary\u0020represeting\u0020a\u0020URL\u0020filter\u0020rule.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_create_filter_rule"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Aget_bool_seb_setting_map\u0028\u0029",
            "name": "get_bool_seb_setting_map",
            "summary": "Map\u0020the\u0020settings\u0020that\u0020are\u0020booleans\u0020to\u0020the\u0020Safe\u0020Exam\u0020Browser\u0020config\u0020keys.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_get_bool_seb_setting_map"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003Asplit_keys\u0028\u0029",
            "name": "split_keys",
            "summary": "This\u0020helper\u0020method\u0020takes\u0020list\u0020of\u0020browser\u0020exam\u0020keys\u0020in\u0020a\u0020string\u0020and\u0020splits\u0020it\u0020into\u0020an\u0020array\u0020of\u0020separate\u0020keys.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#method_split_keys"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003ATABLE",
            "name": "TABLE",
            "summary": "Table\u0020name\u0020for\u0020the\u0020persistent.",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#constant_TABLE"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003A\u0024plist",
            "name": "plist",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#property_plist"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003A\u0024config",
            "name": "config",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#property_config"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\quiz_settings\u003A\u003A\u0024configkey",
            "name": "configkey",
            "summary": "",
            "url": "classes/quizaccess-sebprogram-quiz-settings.html#property_configkey"
        },                {
            "fqsen": "\\quizaccess_sebprogram_override_webservice_execution\u0028\u0029",
            "name": "quizaccess_sebprogram_override_webservice_execution",
            "summary": "Overrides\u0020the\u0020web\u0020service\u0020execution\u0020for\u0020the\u0020quizaccess_sebprogram\u0020plugin.",
            "url": "namespaces/default.html#function_quizaccess_sebprogram_override_webservice_execution"
        },                {
            "fqsen": "\\get_quiz_id\u0028\u0029",
            "name": "get_quiz_id",
            "summary": "Retrieve\u0020the\u0020quiz\u0020ID\u0020associated\u0020with\u0020a\u0020given\u0020course\u0020module\u0020ID.",
            "url": "namespaces/default.html#function_get_quiz_id"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller",
            "name": "program_controller",
            "summary": "Class\u0020for\u0020manipulating\u0020with\u0020the\u0020template\u0020records.",
            "url": "classes/quizaccess-sebprogram-program-controller.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "region_manager\u0020constructor.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method___construct"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Execute\u0020required\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_execute"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aset_external_page\u0028\u0029",
            "name": "set_external_page",
            "summary": "Set\u0020external\u0020page\u0020for\u0020the\u0020manager.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_set_external_page"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aget_instance\u0028\u0029",
            "name": "get_instance",
            "summary": "Return\u0020record\u0020instance.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_get_instance"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aget_instance_dependency\u0028\u0029",
            "name": "get_instance_dependency",
            "summary": "Get\u0020instance\u0020of\u0020program_dependency.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_get_instance_dependency"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Adisplay_all_records\u0028\u0029",
            "name": "display_all_records",
            "summary": "Print\u0020out\u0020all\u0020records\u0020in\u0020a\u0020table.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_display_all_records"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aget_create_button_text\u0028\u0029",
            "name": "get_create_button_text",
            "summary": "Returns\u0020a\u0020text\u0020for\u0020create\u0020new\u0020record\u0020button.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_get_create_button_text"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aget_form\u0028\u0029",
            "name": "get_form",
            "summary": "Returns\u0020form\u0020for\u0020the\u0020record.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_get_form"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aget_view_heading\u0028\u0029",
            "name": "get_view_heading",
            "summary": "View\u0020page\u0020heading\u0020string.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_get_view_heading"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aget_new_heading\u0028\u0029",
            "name": "get_new_heading",
            "summary": "New\u0020record\u0020heading\u0020string.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_get_new_heading"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aget_edit_heading\u0028\u0029",
            "name": "get_edit_heading",
            "summary": "Edit\u0020record\u0020heading\u0020string.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_get_edit_heading"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aget_base_url\u0028\u0029",
            "name": "get_base_url",
            "summary": "Returns\u0020base\u0020URL\u0020for\u0020the\u0020manager.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_get_base_url"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Execute\u0020edit\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_edit"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Execute\u0020delete\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_delete"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aview\u0028\u0029",
            "name": "view",
            "summary": "Execute\u0020view\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_view"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aprint_add_button\u0028\u0029",
            "name": "print_add_button",
            "summary": "Print\u0020out\u0020add\u0020button.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_print_add_button"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aheader\u0028\u0029",
            "name": "header",
            "summary": "Print\u0020out\u0020page\u0020header.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_header"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Afooter\u0028\u0029",
            "name": "footer",
            "summary": "Print\u0020out\u0020the\u0020page\u0020footer.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_footer"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Aget_create_program_button_text\u0028\u0029",
            "name": "get_create_program_button_text",
            "summary": "Get\u0020the\u0020text\u0020for\u0020the\u0020create\u0020program\u0020button.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_get_create_program_button_text"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Acreate_program_dependency\u0028\u0029",
            "name": "create_program_dependency",
            "summary": "Create\u0020program\u0020dependency",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_create_program_dependency"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003Adelete_program_dependency\u0028\u0029",
            "name": "delete_program_dependency",
            "summary": "Delete\u0020program\u0020dependency.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#method_delete_program_dependency"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003AACTION_VIEW",
            "name": "ACTION_VIEW",
            "summary": "View\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#constant_ACTION_VIEW"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003AACTION_ADD",
            "name": "ACTION_ADD",
            "summary": "Add\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#constant_ACTION_ADD"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003AACTION_EDIT",
            "name": "ACTION_EDIT",
            "summary": "Edit\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#constant_ACTION_EDIT"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003AACTION_DELETE",
            "name": "ACTION_DELETE",
            "summary": "Delete\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#constant_ACTION_DELETE"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller\u003A\u003A\u0024output",
            "name": "output",
            "summary": "Locally\u0020cached\u0020\u0024OUTPUT\u0020object.",
            "url": "classes/quizaccess-sebprogram-program-controller.html#property_output"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course",
            "name": "program_controller_course",
            "summary": "Class\u0020for\u0020manipulating\u0020with\u0020the\u0020template\u0020records.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020the\u0020class.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method___construct"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Execute\u0020required\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_execute"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aset_external_page\u0028\u0029",
            "name": "set_external_page",
            "summary": "Set\u0020external\u0020page\u0020for\u0020the\u0020manager.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_set_external_page"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aget_instance\u0028\u0029",
            "name": "get_instance",
            "summary": "Return\u0020record\u0020instance.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_get_instance"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aget_instance_dependency\u0028\u0029",
            "name": "get_instance_dependency",
            "summary": "Get\u0020instance\u0020of\u0020program_dependency",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_get_instance_dependency"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Adisplay_all_records\u0028\u0029",
            "name": "display_all_records",
            "summary": "Print\u0020out\u0020all\u0020records\u0020in\u0020a\u0020table.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_display_all_records"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aget_create_button_text\u0028\u0029",
            "name": "get_create_button_text",
            "summary": "Returns\u0020a\u0020text\u0020for\u0020create\u0020new\u0020record\u0020button.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_get_create_button_text"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aget_form\u0028\u0029",
            "name": "get_form",
            "summary": "Returns\u0020form\u0020for\u0020the\u0020record.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_get_form"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aget_view_heading\u0028\u0029",
            "name": "get_view_heading",
            "summary": "View\u0020page\u0020heading\u0020string.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_get_view_heading"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aget_new_heading\u0028\u0029",
            "name": "get_new_heading",
            "summary": "New\u0020record\u0020heading\u0020string.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_get_new_heading"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aget_edit_heading\u0028\u0029",
            "name": "get_edit_heading",
            "summary": "Edit\u0020record\u0020heading\u0020string.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_get_edit_heading"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aget_base_url\u0028\u0029",
            "name": "get_base_url",
            "summary": "Returns\u0020base\u0020URL\u0020for\u0020the\u0020manager.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_get_base_url"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "A\u0020description\u0020of\u0020the\u0020entire\u0020PHP\u0020function.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_edit"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Execute\u0020delete\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_delete"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aview\u0028\u0029",
            "name": "view",
            "summary": "Execute\u0020view\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_view"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aprint_add_button\u0028\u0029",
            "name": "print_add_button",
            "summary": "Print\u0020out\u0020add\u0020button.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_print_add_button"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aheader\u0028\u0029",
            "name": "header",
            "summary": "Print\u0020out\u0020page\u0020header.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_header"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Afooter\u0028\u0029",
            "name": "footer",
            "summary": "Print\u0020out\u0020the\u0020page\u0020footer.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_footer"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Aget_create_program_button_text\u0028\u0029",
            "name": "get_create_program_button_text",
            "summary": "Returns\u0020a\u0020text\u0020for\u0020create\u0020new\u0020record\u0020button.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_get_create_program_button_text"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Acreate_program_dependency\u0028\u0029",
            "name": "create_program_dependency",
            "summary": "Create\u0020program\u0020dependency",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_create_program_dependency"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003Adelete_program_dependency\u0028\u0029",
            "name": "delete_program_dependency",
            "summary": "Deletes\u0020program\u0020dependencies\u0020based\u0020on\u0020given\u0020parameters.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#method_delete_program_dependency"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003AACTION_VIEW",
            "name": "ACTION_VIEW",
            "summary": "View\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#constant_ACTION_VIEW"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003AACTION_ADD",
            "name": "ACTION_ADD",
            "summary": "Add\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#constant_ACTION_ADD"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003AACTION_EDIT",
            "name": "ACTION_EDIT",
            "summary": "Edit\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#constant_ACTION_EDIT"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003AACTION_DELETE",
            "name": "ACTION_DELETE",
            "summary": "Delete\u0020action.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#constant_ACTION_DELETE"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003A\u0024courseid",
            "name": "courseid",
            "summary": "Course\u0020id.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#property_courseid"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\program_controller_course\u003A\u003A\u0024output",
            "name": "output",
            "summary": "Locally\u0020cached\u0020\u0024OUTPUT\u0020object.",
            "url": "classes/quizaccess-sebprogram-program-controller-course.html#property_output"
        },                {
            "fqsen": "\\quizaccess_sebprogram",
            "name": "quizaccess_sebprogram",
            "summary": "A\u0020rule\u0020requiring\u0020the\u0020student\u0020to\u0020promise\u0020not\u0020to\u0020cheat.",
            "url": "classes/quizaccess-sebprogram.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\u003A\u003Amake\u0028\u0029",
            "name": "make",
            "summary": "Return\u0020an\u0020appropriately\u0020configured\u0020instance\u0020of\u0020this\u0020rule,\u0020if\u0020it\u0020is\u0020applicable\nto\u0020the\u0020given\u0020quiz,\u0020otherwise\u0020return\u0020null.",
            "url": "classes/quizaccess-sebprogram.html#method_make"
        },                {
            "fqsen": "\\quizaccess_sebprogram\u003A\u003Aget_link\u0028\u0029",
            "name": "get_link",
            "summary": "Get\u0020the\u0020link\u0020for\u0020the\u0020quiz\u0020access\u0020rule\u0020SEB\u0020program.",
            "url": "classes/quizaccess-sebprogram.html#method_get_link"
        },                {
            "fqsen": "\\quizaccess_sebprogram\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "Information,\u0020such\u0020as\u0020might\u0020be\u0020shown\u0020on\u0020the\u0020quiz\u0020view\u0020page,\u0020relating\u0020to\u0020this\u0020restriction.",
            "url": "classes/quizaccess-sebprogram.html#method_description"
        },                {
            "fqsen": "\\quizaccess_sebprogram\u003A\u003Aadd_settings_form_fields\u0028\u0029",
            "name": "add_settings_form_fields",
            "summary": "Add\u0020settings\u0020form\u0020fields\u0020to\u0020the\u0020quiz\u0020form.",
            "url": "classes/quizaccess-sebprogram.html#method_add_settings_form_fields"
        },                {
            "fqsen": "\\quizaccess_sebprogram\u003A\u003Asave_settings\u0028\u0029",
            "name": "save_settings",
            "summary": "Save\u0020settings\u0020for\u0020the\u0020quiz.",
            "url": "classes/quizaccess-sebprogram.html#method_save_settings"
        },                {
            "fqsen": "\\quizaccess_sebprogram\u003A\u003Adelete_settings\u0028\u0029",
            "name": "delete_settings",
            "summary": "Delete\u0020settings.",
            "url": "classes/quizaccess-sebprogram.html#method_delete_settings"
        },                {
            "fqsen": "\\behat_sebprogram",
            "name": "behat_sebprogram",
            "summary": "hybridteaching\u002Drelated\u0020steps\u0020definitions.",
            "url": "classes/behat-sebprogram.html"
        },                {
            "fqsen": "\\behat_sebprogram\u003A\u003Ai_type_in_focused_autocomplete_using_javascript\u0028\u0029",
            "name": "i_type_in_focused_autocomplete_using_javascript",
            "summary": "",
            "url": "classes/behat-sebprogram.html#method_i_type_in_focused_autocomplete_using_javascript"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram",
            "name": "quizaccess_sebprogram",
            "summary": "",
            "url": "namespaces/quizaccess-sebprogram.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\event",
            "name": "event",
            "summary": "",
            "url": "namespaces/quizaccess-sebprogram-event.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\form",
            "name": "form",
            "summary": "",
            "url": "namespaces/quizaccess-sebprogram-local-form.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local",
            "name": "local",
            "summary": "",
            "url": "namespaces/quizaccess-sebprogram-local.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\local\\table",
            "name": "table",
            "summary": "",
            "url": "namespaces/quizaccess-sebprogram-local-table.html"
        },                {
            "fqsen": "\\quizaccess_sebprogram\\privacy",
            "name": "privacy",
            "summary": "",
            "url": "namespaces/quizaccess-sebprogram-privacy.html"
        }            ]
);
